# Generated by Django 4.2.5 on 2023-10-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_group_subject_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
